[package]
name = "funds_data_scraper"
version = "0.1.0"
authors = ["ramba_enc4ybi"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.10", features = ["blocking", "json"] }
scraper = "0.12.0"
